### ISSUE TITLE
could you share the heparin data of 137 antibodies , I only found 22 in the paper~

### ISSUE THREAD

**Issue by kehan777** [liedllab/surface_analyses#12]
Could you share the heparin data of 137 antibodies , I only found 22 in the paper，thank you very much~
We used heparin data from Kraft et al.17 for a set of 137 antibodies described in the dataset by Jain et al.27

17
Kraft, T. E.; Richter, W. F.; Emrich, T.; Knaupp, A.; Schuster, M.; Wolfert, A.; Kettenberger, 
H. Heparin Chromatography as an in Vitro Predictor for Antibody Clearance Rate through 
Pinocytosis. mAbs 2020, 12 (1), 1683432. https://doi.org/10.1080/19420862.2019.1683432
27
Jain, T.; Sun, T.; Durand, S.; Hall, A.; Houston, N. R.; Nett, J. H.; Sharkey, B.; Bobrowicz, 
B.; Caffry, I.; Yu, Y.; Cao, Y.; Lynaugh, H.; Brown, M.; Baruah, H.; Gray, L. T.; Krauland, 
E. M.; Xu, Y.; Vásquez, M.; Wittrup, K. D. Biophysical Properties of the Clinical-Stage 
Antibody Landscape. Proc Natl Acad Sci USA 2017, 114 (5), 944. 
https://doi.org/10.1073/pnas.1616408114.

**Comment by fwaibl** [comment]
Hi,

thanks for your interest in our work. The full dataset of (relative) heparin retention times is in Supplementary Table 2 in the paper by Kraft et al.

Best,
Franz
