### ISSUE TITLE
Is the trajs file necessary and how to generate it ?

### ISSUE THREAD

**Issue by kehan777** [liedllab/surface_analyses#25]
pep_patch_electrostatic apbs-input.pdb --apbs_dir apbs --ply_out potential -o patches
.csv
usage: pep_patch_electrostatic [-h] [--ref REF] [--protein_ref PROTEIN_REF] [--stride STRIDE] [--dx [DX]]
                               [--apbs_dir APBS_DIR] [--probe_radius PROBE_RADIUS] [-o OUT]
                               [-c PATCH_CUTOFF PATCH_CUTOFF] [-ic INTEGRAL_CUTOFF INTEGRAL_CUTOFF]
                               [--surface_type {sas,ses,gauss}] [--ply_out PLY_OUT] [--pos_patch_cmap POS_PATCH_CMAP]
                               [--neg_patch_cmap NEG_PATCH_CMAP] [--ply_cmap PLY_CMAP] [--ply_clim PLY_CLIM PLY_CLIM]
                               [--check_cdrs] [-n N_PATCHES] [-s SIZE_CUTOFF] [--gauss_shift GAUSS_SHIFT]
                               [--gauss_scale GAUSS_SCALE] [--pH PH] [--ion_species [ION_SPECIES ...]]
                               parm trajs [trajs ...]
pep_patch_electrostatic: error: the following arguments are required: trajs

Q: Is the trajs file necessary and how to generate it ? by gromacs  MD ..?

**Comment by fwaibl** [comment]
Hi. We recently changed the code to use the same loading function as the _hydrophobic script, and that's why we now ask for a topology and trajectory.
If you have a PDB file, you can supply the same file twice, once as topology and once as trajectory. But I agree that this is currently very confusing. We should make it optional, and use the "parm" file as a default.

I hope this helps.

Best,
Franz

**Comment by vhoer** [comment]
For your example, the input would then be the following:
pep_patch_electrostatic apbs-input.pdb apbs-input.pdb --apbs_dir apbs --ply_out potential -o patches.csv

**Comment by fwaibl** [comment]
Yes, that is correct. We will change the README accordingly (and probably update the commandline interface soon). Thanks for pointing this out.

**Comment by kehan777** [comment]
Error: pdb2pqr failed:
pdb2pqr stdout:
b''
pdb2pqr stderr:
b'INFO:PDB2PQR v3.6.1: biomolecular structure conversion software.\nINFO:Please cite:  Jurrus E, et al.  Improvements to the APBS biomolecular solvation software suite.  Protein Sci 27 112-128 (2018).\nINFO:Please cite:  Dolinsky TJ, et al.  PDB2PQR: expanding and upgrading automated preparation of biomolecular structures for molecular simulations. Nucleic Acids Res 35 W522-W525 (2007).\nINFO:Checking and transforming input arguments.\nINFO:Loading topology files.\nINFO:Loading molecule: input.pdb\nINFO:Setting up molecule.\nWARNING:Unable to find amino or nucleic acid definition for NME.  Parsing as new residue.\nWARNING:Unable to find amino or nucleic acid definition for NME.  Parsing as new residue.\nINFO:Created biomolecule object with 229 residues and 3449 atoms.\nINFO:Setting termini states for biomolecule chains.\nINFO:Loading forcefield.\nINFO:Loading hydrogen topology definitions.\nINFO:This biomolecule is clean.  No repair needed.\nINFO:Updating disulfide bridges.\nINFO:Debumping biomolecule.\nINFO:Adding hydrogens to biomolecule.\nINFO:Debumping biomolecule (again).\nINFO:Optimizing hydrogen bonds\nINFO:Applying force field to biomolecule states.\nWARNING:Residue NME A 121 has non-integer charge: -0.1438 deviates by 0.1438 from integral, exceeding error tolerance 0.001. \nWARNING:Residue NME B 229 has non-integer charge: -0.1438 deviates by 0.1438 from integral, exceeding error tolerance 0.001. \nWARNING:Residue NME A 121 has non-integer charge:  -0.1438 deviates by 0.1438 from integral, exceeding error tolerance 0.001\nWARNING:Residue NME B 229 has non-integer charge:  -0.1438 deviates by 0.1438 from integral, exceeding error tolerance 0.001\nCRITICAL:4.712400000000001 deviates by 0.2875999999999994 from integral, exceeding error tolerance 0.001\nCRITICAL:Giving up.\nTraceback (most recent call last):\n  File "/home/AB/conda3/envs/ab/lib/python3.10/site-packages/pdb2pqr/main.py", line 792, in main_driver\n    results = non_trivial(\n  File "/home/AB/conda3/envs/ab/lib/python3.10/site-packages/pdb2pqr/main.py", line 705, in non_trivial\n    raise ValueError(charge_err)\nValueError: 4.712400000000001 deviates by 0.2875999999999994 from integral, exceeding error tolerance 0.001\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/home/AB/conda3/envs/ab/bin/pdb2pqr", line 33, in <module>\n    sys.exit(load_entry_point(\'pdb2pqr==3.6.1\', \'console_scripts\', \'pdb2pqr\')())\n  File "/home/AB/conda3/envs/ab/lib/python3.10/site-packages/pdb2pqr/main.py", line 829, in main\n    if main_driver(args) == 1:\n  File "/home/AB/conda3/envs/ab/lib/python3.10/site-packages/pdb2pqr/main.py", line 802, in main_driver\n    raise RuntimeError from err\nRuntimeError\n'
Traceback (most recent call last):
  File "/home/AB/conda3/envs/ab/bin/pep_patch_electrostatic", line 33, in <module>
    sys.exit(load_entry_point('Surface-analyses==0.1', 'console_scripts', 'pep_patch_electrostatic')())
  File "/home/AB/conda3/envs/ab/lib/python3.10/site-packages/surface_analyses/commandline_electrostatic.py", line 159, in main
    griddata = get_apbs_potential_from_mdtraj(traj, args.apbs_dir, args.pH, ion_species)
  File "/home/AB/conda3/envs/ab/lib/python3.10/site-packages/surface_analyses/commandline_electrostatic.py", line 311, in get_apbs_potential_from_mdtraj
    raise RuntimeError("pdb2pqr failed")
RuntimeError: pdb2pqr failed


>>The error message indicates that pdb2pqr failed due to a non-integer charge deviation exceeding the error tolerance. You may need to review the input PDB file and the residues causing the non-integer charges. Additionally, adjusting the error tolerance or checking for any issues in the input file could help resolve the problem. could you tell me how to solve it?

**Comment by kehan777** [comment]
another question, commandline_electrostatic.py line 355, do i need to setup AMBER force file?
def run_pdb2pqr(pdbfile, cwd=".", ff="AMBER", name_base="apbs", pH=None):
    if not isinstance(cwd, pathlib.Path):
        cwd = pathlib.Path(cwd)
    command = ["pdb2pqr", f"--ff={ff}", pdbfile, name_base + ".pqr", "--apbs-input", "apbs.in"]
    if pH is not None:
        command.extend(["--titration-state-method=propka", f"--with-ph={pH}"])
    process = subprocess.run(
        command,
        capture_output=True,
        cwd=cwd,
    )
    return process

**Comment by kehan777** [comment]
pep_patch_electrostatic 339Ehui.pdb 339Ehui.pdb --apbs_dir ~/surface-ana --ply_out potential -o patches.csv
pep_patch_electrostatic, 02/15/2024, 12:44:53

Command line arguments:
/home/AB/conda3/envs/ab/bin/pep_patch_electrostatic 339Ehui.pdb 339Ehui.pdb --apbs_dir /home/adsb/surface-ana --ply_out potential -o patches.csv
Traceback (most recent call last):
  File "/home/AB/conda3/envs/ab/bin/pep_patch_electrostatic", line 33, in <module>
    sys.exit(load_entry_point('Surface-analyses==0.1', 'console_scripts', 'pep_patch_electrostatic')())
  File "/home/AB/conda3/envs/ab/lib/python3.10/site-packages/surface_analyses/commandline_electrostatic.py", line 159, in main
    griddata = get_apbs_potential_from_mdtraj(traj, args.apbs_dir, args.pH, ion_species)
  File "/home/AB/conda3/envs/ab/lib/python3.10/site-packages/surface_analyses/commandline_electrostatic.py", line 313, in get_apbs_potential_from_mdtraj
    apbs = run_apbs("apbs.in", cwd=run_dir)
  File "/home/AB/conda3/envs/ab/lib/python3.10/site-packages/surface_analyses/commandline_electrostatic.py", line 372, in run_apbs
    process = subprocess.run(
  File "/home/AB/conda3/envs/ab/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/AB/conda3/envs/ab/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/AB/conda3/envs/ab/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'apbs'

**Comment by fwaibl** [comment]
That seems like a problem with the PDB that is written out from mdtraj. Do you have non-standard amino acids in the PDB file? If that is possible, you could send us the PDB file and we could try to have a look at it.

We recently changed the way in which we treat the input. Could you try using the 0.2.0 version? In that case, you would only have to use the PDB file once, and it should get used as it is.
If that solves the problem, we might have to think about reverting that change, or find another way to preserve the residue/atom naming.

**Comment by vhoer** [comment]
The problem is most likely, that your PDB contains a NME capping residue which is appearently not supported by pdb2pqr - maybe remove it for the analysis?

**Comment by kehan777** [comment]
yes  https://github.com/liedllab/surface_analyses/blob/main/test/trastuzumab/apbs-input.pdb, PDB contains a NME capping, remove it for the analysis is ok ,thank you~
