### ISSUE TITLE
How to understand the results?

### ISSUE THREAD

**Issue by kehan777** [liedllab/surface_analyses#27]
pep_patch_electrostatic lenzilumab.pdb lenzilumab.pdb --apbs_dir ~/surface-ana/lenzilumab --ply_out potential -o patches.csv

Integrals (total, ++, +, -, --):
50482.40851287833 35776.26115315687 57389.25321048668 -6906.844697608349 -3304.059161243011

    voxel_volume = griddata.grid.voxel_volume
    accessible_data = griddata[columns[0]].values[accessible]
    integral = np.sum(accessible_data) * voxel_volume
    integral_high = np.sum(np.maximum(accessible_data - args.integral_cutoff[0], 0)) * voxel_volume
    integral_pos = np.sum(np.maximum(accessible_data, 0)) * voxel_volume
    integral_neg = np.sum(np.minimum(accessible_data, 0)) * voxel_volume
    integral_low = np.sum(np.minimum(accessible_data - args.integral_cutoff[1], 0)) * voxel_volume
    print('Integrals (total, ++, +, -, --):')
    print(f'{integral} {integral_high} {integral_pos} {integral_neg} {integral_low}')

Is the Positive Integral in the article the integral_pos in the above code?
 how to Convert the result to  Positive Integral [keTe-nm³] ,Is there any formula?
![image](https://github.com/liedllab/surface_analyses/assets/19143496/e955146a-9add-4b5d-a8ea-8b1e11f75ee6)

how to use patch.csv result, mark the depth of the color on pymol
type | npoints | area | cdr | main_residue
positive | 11502 | 1720.623 | FALSE | LYS212
positive | 1303 | 191.1711 | FALSE | LYS63
positive | 995 | 148.1352 | FALSE | ARG164
positive | 976 | 147.7599 | FALSE | LYS13
positive | 610 | 87.9072 | FALSE | ARG137
...
negative | 583 | 85.74826 | FALSE | LYS226
negative | 513 | 76.24546 | FALSE | GLU200

thank you!

**Comment by fwaibl** [comment]
Hi,

yes, `integral_pos` is the positive integral. Compared to the paper, there is a unit conversion from [kT e^-1 Å^3] to to [kT e^-1 nm^3], so you need to divide by 1000. Indeed, we should add the units to the commandline output.

It is not clear to me what you want to do with the `patch.csv` file. For visualization in Pymol, you should use the .ply file rather than the csv.

**Comment by kehan777** [comment]
get it, thank you, 新春大吉，恭喜发财！😀
